# Generated by Django 4.1.4 on 2023-02-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Second_Name', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('E_mail', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
            ],
        ),
    ]
