# Generated by Django 4.1.4 on 2023-02-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('COD', 'COD'), ('Debit/Credit_Card', 'Debit/Credit_Card'), ('UPI', 'UPI')], default='COD', max_length=100),
        ),
    ]
