# Generated by Django 4.1.4 on 2023-02-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='first_name',
            new_name='productmodel',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='last_name',
            new_name='productname',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='email',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='phone',
        ),
        migrations.AddField(
            model_name='manager',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
