# Generated by Django 4.1.4 on 2023-02-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_first_name_manager_productmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manager',
            new_name='AddPro',
        ),
    ]
