# Generated by Django 4.1.4 on 2023-02-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_addpro_id_alter_addpro_productname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('productmodel', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('pic', models.ImageField(null=True, upload_to='profilepic')),
            ],
        ),
        migrations.DeleteModel(
            name='AddPro',
        ),
    ]
